deactivate other tests
#26

diff --git a/.github/workflows/testing-special-issues.yml b/.github/workflows/testing-special-issues.yml
--- a/.github/workflows/testing-special-issues.yml
+++ b/.github/workflows/testing-special-issues.yml
@@ -1,73 +1,73 @@
-# This is a basic workflow to help you get started with Actions
-
-name: Testing special issues
-
-# Controls when the action will run. Triggers the workflow on push or pull request
-# events but only for the main branch
-on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
-  workflow_dispatch: {}
-
-# A workflow run is made up of one or more jobs that can run sequentially or in parallel
-jobs:
-  special-powershell:
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v4.1.0
-      - name: Download Special Issues windows
-        id: specialIssues
-        shell: pwsh
-        run: ./windows/magpi-special-issue-downloader.ps1
-      - name: lslah issues
-        run: Get-ChildItem –path D:\a\MagPiDownloader\MagPiDownloader\windows\special_issues
-      - name: "Check file existence Windows special"
-        id: check_files
-        uses: andstor/file-existence-action@v2.0.0
-        with:
-          files: "./windows/special_issues/Essentials_Games_v1.pdf"
-          fail: true
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
-
-  special-bash-linux:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4.1.0
-      - name: Download Special Issues linux
-        id: specialIssues
-        run: bash ./linux_mac/magpi-special-issue-downloader.sh
-
-      - name: "Check file existence Linux special issues"
-        id: check_files
-        uses: andstor/file-existence-action@v2.0.0
-        with:
-          files: "special_issues/MagPiSE1.pdf, special_issues/Projects_Book_v3.pdf, special_issues/Retro_Gaming.pdf, special_issues/C_and_GUI_Programming_2nd_Edition.pdf"
-          fail: true
-      - name: lslah
-        run: ls -lah special_issues/
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
-  special-bash-macos:
-    runs-on: macos-latest
-    steps:
-      - uses: actions/checkout@v4.1.0
-      - name: Download Special Issues Mac
-        id: specialIssues
-        run: bash ./linux_mac/magpi-special-issue-downloader.sh
-# check if files are existing
-      - name: "Check file existence MacOs special issues"
-        id: check_files
-        uses: andstor/file-existence-action@v2.0.0
-        with:
-          files: "special_issues/MagPiSE1.pdf, special_issues/Projects_Book_v3.pdf, special_issues/Retro_Gaming.pdf, special_issues/C_and_GUI_Programming_2nd_Edition.pdf"
-          fail: true
-      - name: lslah
-        run: ls -lah special_issues/
-      - name: File exists
-        if: steps.check_files.outputs.files_exists == 'false'
-        run: exit 1
+## This is a basic workflow to help you get started with Actions
+#
+#name: Testing special issues
+#
+## Controls when the action will run. Triggers the workflow on push or pull request
+## events but only for the main branch
+#on:
+#  push:
+#    branches: [ main ]
+#  pull_request:
+#    branches: [ main ]
+#  workflow_dispatch: {}
+#
+## A workflow run is made up of one or more jobs that can run sequentially or in parallel
+#jobs:
+#  special-powershell:
+#    runs-on: windows-latest
+#    steps:
+#      - uses: actions/checkout@v4.1.0
+#      - name: Download Special Issues windows
+#        id: specialIssues
+#        shell: pwsh
+#        run: ./windows/magpi-special-issue-downloader.ps1
+#      - name: lslah issues
+#        run: Get-ChildItem –path D:\a\MagPiDownloader\MagPiDownloader\windows\special_issues
+#      - name: "Check file existence Windows special"
+#        id: check_files
+#        uses: andstor/file-existence-action@v2.0.0
+#        with:
+#          files: "./windows/special_issues/Essentials_Games_v1.pdf"
+#          fail: true
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
+#
+#  special-bash-linux:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - uses: actions/checkout@v4.1.0
+#      - name: Download Special Issues linux
+#        id: specialIssues
+#        run: bash ./linux_mac/magpi-special-issue-downloader.sh
+#
+#      - name: "Check file existence Linux special issues"
+#        id: check_files
+#        uses: andstor/file-existence-action@v2.0.0
+#        with:
+#          files: "special_issues/MagPiSE1.pdf, special_issues/Projects_Book_v3.pdf, special_issues/Retro_Gaming.pdf, special_issues/C_and_GUI_Programming_2nd_Edition.pdf"
+#          fail: true
+#      - name: lslah
+#        run: ls -lah special_issues/
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
+#  special-bash-macos:
+#    runs-on: macos-latest
+#    steps:
+#      - uses: actions/checkout@v4.1.0
+#      - name: Download Special Issues Mac
+#        id: specialIssues
+#        run: bash ./linux_mac/magpi-special-issue-downloader.sh
+## check if files are existing
+#      - name: "Check file existence MacOs special issues"
+#        id: check_files
+#        uses: andstor/file-existence-action@v2.0.0
+#        with:
+#          files: "special_issues/MagPiSE1.pdf, special_issues/Projects_Book_v3.pdf, special_issues/Retro_Gaming.pdf, special_issues/C_and_GUI_Programming_2nd_Edition.pdf"
+#          fail: true
+#      - name: lslah
+#        run: ls -lah special_issues/
+#      - name: File exists
+#        if: steps.check_files.outputs.files_exists == 'false'
+#        run: exit 1
