adds tests for checking if the files are different

diff --git a/.github/workflows/testing-regular-issues.yml b/.github/workflows/testing-regular-issues.yml
--- a/.github/workflows/testing-regular-issues.yml
+++ b/.github/workflows/testing-regular-issues.yml
@@ -81,3 +81,12 @@ jobs:
         if: steps.check_files.outputs.files_exists == 'false'
         run: exit 1
 
+      - name: "check if files are all different"
+        id: md5_files
+        shell: bash
+        run: |
+          cmp --silent issues/MagPi_1.pdf issues/MagPi_2.pdf && echo '### ERROR: Files Are Identical! && exit 1' 
+          cmp --silent issues/MagPi_2.pdf issues/MagPi_${{ env.ISSUE_MINUS_SIX }}.pdf && echo '### ERROR: Files Are Identical! && exit 1'
+          cmp --silent issues/MagPi_${{ env.ISSUE_MINUS_SIX }}.pdf issues/MagPi_${{ env.ISSUE_MINUS_FIVE }}.pdf && echo '### ERROR: Files Are Identical! && exit 1'
+          cmp --silent issues/MagPi_${{ env.ISSUE_MINUS_FIVE }}.pdf issues/MagPi_${{ env.ISSUE_MINUS_ONE }}.pdf && echo '### ERROR: Files Are Identical! && exit 1'
+          cmp --silent issues/MagPi_${{ env.ISSUE_MINUS_ONE }}.pdf issues/MagPi_${{ env.ISSUE_NUMBER }}.pdf && echo '### ERROR: Files Are Identical! && exit 1'
